# Generated by Django 4.0.3 on 2022-03-29 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.regions')),
            ],
            options={
                'verbose_name_plural': 'Fruits',
            },
        ),
    ]
